export const FETCH_AUTH = 'FETCH_AUTH';
export const FETCH_REGISTRATION = 'FETCH_REGISTRATION';
export const FETCH_CHECK_EMAIL = 'FETCH_CHECK_EMAIL';
export const FETCH_CONFIRM = 'FETCH_CONFIRM';
export const FETCH_CHANGE_PASSWORD = 'FETCH_CHANGE_PASSWORD';
